'use client';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, MapPin, RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import apiClient from '@/lib/api-client';
import { useAuthStore } from '@/lib/store/auth-store';
import { OperationsShell } from '@/components/operations-shell';
type Incident={id:string;title?:string;type?:string;description?:string;severity?:string;status?:string;reported_at?:string;location?:{name?:string}};
export default function IncidentDetailPage(){const {id}=useParams<{id:string}>();const router=useRouter();const {token,isAuthenticated,hasHydrated}=useAuthStore();const [item,setItem]=useState<Incident>();const [error,setError]=useState('');const load=useCallback(async()=>{try{setError('');const r=await apiClient.get(`/incidents/${id}`);setItem(r.data.data);}catch{setError('This incident could not be loaded.');}},[id]);useEffect(()=>{if(!hasHydrated)return;if(!isAuthenticated||!token){router.push('/login');return;}load();},[hasHydrated,isAuthenticated,token,router,load]);if(!hasHydrated||!isAuthenticated)return null;return <OperationsShell eyebrow="Response coordination" title="Incident Details"><Link className="detail-back" href="/incidents"><ArrowLeft size={15}/>Back to incidents</Link>{error?<div className="data-error">{error}<button onClick={load}>Retry</button></div>:!item?<div className="data-loading">Loading incident…</div>:<><section className="page-summary"><div><span>Current status</span><strong>{item.status||'REPORTED'}</strong></div><div><span>Severity</span><strong className="danger-text">{item.severity||'UNSPECIFIED'}</strong></div><div><span>Reported</span><strong>{item.reported_at?new Date(item.reported_at).toLocaleDateString():'—'}</strong></div><button onClick={load}><RefreshCw size={15}/>Refresh</button></section><section className="data-panel" style={{padding:22}}><div style={{display:'flex',gap:14,alignItems:'center',borderBottom:'1px solid #e7edf5',paddingBottom:18}}><span className="alert-symbol"><AlertTriangle size={22}/></span><div><h2 style={{margin:0}}>{item.title||item.type||'Field incident'}</h2><p style={{margin:'5px 0 0',color:'#6a7890',fontSize:12}}>{item.type||'Incident'} · {item.id}</p></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14,marginTop:18}}><article className="data-panel" style={{padding:16}}><AlertTriangle size={18}/><h3>Incident overview</h3><p>{item.description||'No field description has been submitted.'}</p></article><article className="data-panel" style={{padding:16}}><MapPin size={18}/><h3>Reported location</h3><p>{item.location?.name||'Location data is not available.'}</p></article></div></section></>}</OperationsShell>}
