'use client';
import Link from 'next/link';
import { Activity, ArrowRight, Radio, RefreshCw, WifiOff } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import apiClient from '@/lib/api-client';
import { useAuthStore } from '@/lib/store/auth-store';
import { OperationsShell } from '@/components/operations-shell';
type Sensor={id:string;name?:string;serial_number?:string;type?:string;status?:string;battery_level?:number;last_seen?:string};
export default function SensorsPage(){const router=useRouter();const {token,isAuthenticated,hasHydrated}=useAuthStore();const [items,setItems]=useState<Sensor[]>([]);const [error,setError]=useState('');const load=useCallback(async()=>{try{setError('');const r=await apiClient.get('/devices');setItems(r.data.data||[]);}catch{setError('Sensor network data is unavailable.');}},[]);useEffect(()=>{if(!hasHydrated)return;if(!isAuthenticated||!token){router.push('/login');return;}load();},[hasHydrated,isAuthenticated,token,router,load]);if(!hasHydrated||!isAuthenticated)return null;const online=items.filter(i=>i.status==='ONLINE').length;return <OperationsShell eyebrow="CrisisMesh sensor network" title="Sensors Dashboard"><section className="page-summary"><div><span>Total sensors</span><strong>{items.length}</strong></div><div><span>Online</span><strong className="safe-text">{online}</strong></div><div><span>Network health</span><strong>{items.length?`${Math.round(online/items.length*100)}%`:'—'}</strong></div><button onClick={load}><RefreshCw size={15}/>Refresh</button></section><section className="data-panel"><div className="data-toolbar"><div><h2>Sensor network</h2><p>Live availability and telemetry entry points for field sensors.</p></div></div>{error?<div className="data-error">{error}<button onClick={load}>Retry</button></div>:items.length===0?<div className="data-empty"><WifiOff size={26}/>No sensors are available.</div>:<div className="device-grid">{items.map(s=><Link className="device-card" style={{textDecoration:'none',color:'inherit'}} href={`/sensors/${s.id}`} key={s.id}><div className={`device-icon ${s.status==='ONLINE'?'online':''}`}><Radio size={19}/></div><div className="device-card-main"><h3>{s.name||s.serial_number||'Field sensor'}</h3><p>{s.type||'Sensor'} · {s.serial_number||s.id}</p><span className={`state-badge ${s.status==='ONLINE'?'online':''}`}>{s.status||'UNKNOWN'}</span></div><div className="device-meta"><span><Activity size={14}/>{s.battery_level==null?'—':`${s.battery_level}%`}</span><ArrowRight size={16}/></div></Link>)}</div>}</section></OperationsShell>}
