'use client';
import Link from 'next/link';
import { Activity, ArrowLeft, MapPin, Radio, RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import apiClient from '@/lib/api-client';
import { useAuthStore } from '@/lib/store/auth-store';
import { OperationsShell } from '@/components/operations-shell';
type Sensor={id:string;name?:string;serial_number?:string;type?:string;status?:string;battery_level?:number;signal_strength?:number;last_seen?:string;location?:{name?:string}};
export default function SensorDetailPage(){const {id}=useParams<{id:string}>();const router=useRouter();const {token,isAuthenticated,hasHydrated}=useAuthStore();const [sensor,setSensor]=useState<Sensor>();const [error,setError]=useState('');const load=useCallback(async()=>{try{setError('');const r=await apiClient.get(`/devices/${id}`);setSensor(r.data.data);}catch{setError('This sensor could not be loaded.');}},[id]);useEffect(()=>{if(!hasHydrated)return;if(!isAuthenticated||!token){router.push('/login');return;}load();},[hasHydrated,isAuthenticated,token,router,load]);if(!hasHydrated||!isAuthenticated)return null;return <OperationsShell eyebrow="CrisisMesh sensor network" title="Sensor Details"><Link className="detail-back" href="/sensors"><ArrowLeft size={15}/>Back to all sensors</Link>{error?<div className="data-error">{error}<button onClick={load}>Retry</button></div>:!sensor?<div className="data-loading">Loading sensor…</div>:<><section className="page-summary"><div><span>Sensor status</span><strong className={sensor.status==='ONLINE'?'safe-text':'danger-text'}>{sensor.status||'UNKNOWN'}</strong></div><div><span>Battery level</span><strong>{sensor.battery_level==null?'—':`${sensor.battery_level}%`}</strong></div><div><span>Signal strength</span><strong>{sensor.signal_strength==null?'—':`${sensor.signal_strength} dBm`}</strong></div><button onClick={load}><RefreshCw size={15}/>Refresh</button></section><section className="data-panel" style={{padding:22}}><div style={{display:'flex',gap:14,alignItems:'center',borderBottom:'1px solid #e7edf5',paddingBottom:18}}><span className="device-icon online"><Radio size={22}/></span><div><h2 style={{margin:0}}>{sensor.name||sensor.serial_number||'Field sensor'}</h2><p style={{margin:'5px 0 0',color:'#6a7890',fontSize:12}}>{sensor.type||'Sensor'} · {sensor.serial_number||sensor.id}</p></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14,marginTop:18}}><article className="data-panel" style={{padding:16}}><Activity size={18}/><h3>Latest signal</h3><p>{sensor.last_seen?new Date(sensor.last_seen).toLocaleString():'No latest signal available.'}</p></article><article className="data-panel" style={{padding:16}}><MapPin size={18}/><h3>Sensor location</h3><p>{sensor.location?.name||'Location data is not available.'}</p></article></div></section></>}</OperationsShell>}
